[package]
name = "mic-auth-server-summoners-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1-rc.3"
serde = { version = "1.0.127", features = ["derive"]}
canyon_sql = { version = "0.5.1", features = ["postgres"]}
