#! Note that this docker-compose file is intented to be used only in a local-dev enviroment!

services:
  postgres:
    image: postgres:17
    container_name: pg_auth_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zerodaycode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - dev_network

volumes:
  postgres_data:

networks:
  dev_network:
